services:

  postgres_db:
    image: "postgres:16"
    container_name: server_db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./server/initdb/:/docker-entrypoint-initdb.d/
      - server_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    #    networks:
    #      - server_net
    network_mode: "host"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  server:
    build:
      context: .
      dockerfile: Dockerfile
    #    ports:
    #      - "127.0.0.1:9876:9876"
    environment:
      - PORT="8000"
      - HOST="127.0.0.1"
    network_mode: "host"

    depends_on:
      postgres_db:
        condition: service_healthy

#    networks:
#      - server_net

networks:
  server_net:
    name: server_net

volumes:
  server_db-data: