services:

  postgres_db:
    image: "postgres:16"
    container_name: server_db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./server/init_db:/docker-entrypoint-initdb.d
      - sever_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - server_net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  server:
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - server_net

networks:
  server_net:
    name: server_net

volumes:
  server_db-data: